#!/usr/bin/bash
#
# Credits: @hrdnxxxX
# FROM FileTeleForce <https://github.com/hrdn-dev/FileYeleForfe/>
# t.me/TeleFileForfe & t.me/hrdnxxxX

# Attemp to Terminate and Remove previous session
if [ ! -d .git ]; then
    git clone https://github.com/hrdn-dev/FileTeleForce -b master tmp_git
    mv tmp_git/.git .
    rm -rf tmp_git
fi

# start
python3 main.py
